#!/usr/bin/env bash
# =============================================================================
# ComplianceOS — One-Command Docker Install
# =============================================================================
# Run:
#   curl -fsSL https://raw.githubusercontent.com/sectutor/ComplianceOS/main/deploy/docker/install.sh | bash
#
# Or with env overrides:
#   curl -fsSL https://raw.githubusercontent.com/sectutor/ComplianceOS/main/deploy/docker/install.sh | \
#     bash -s -- -p 8080 -k my-encryption-key
# =============================================================================
set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/sectutor/ComplianceOS.git"
BRANCH="main"
TARGET_DIR="${HOME}/complianceos"
PORT="${PORT:-3002}"
ENCRYPTION_KEY="${APP_ENCRYPTION_KEY:-}"
COMPOSE_FILE="docker-compose.selfhost.yml"

# Parse CLI flags
while [[ $# -gt 0 ]]; do
  case "$1" in
    -d|--dir)       TARGET_DIR="$2"; shift 2 ;;
    -p|--port)      PORT="$2";        shift 2 ;;
    -k|--key)       ENCRYPTION_KEY="$2"; shift 2 ;;
    -b|--branch)    BRANCH="$2";      shift 2 ;;
    -h|--help)      echo "Usage: $0 [-d dir] [-p port] [-k encryption_key] [-b branch]"; exit 0 ;;
    *)              echo "Unknown: $1"; exit 1 ;;
  esac
done

echo "╔══════════════════════════════════════════════╗"
echo "║     ComplianceOS — Docker Install            ║"
echo "╚══════════════════════════════════════════════╝"

# ── Prerequisites ────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || {
  echo "❌ Docker not found. Install Docker first:"
  echo "   https://docs.docker.com/engine/install/"
  exit 1
}

# ── Clone ────────────────────────────────────────────────────────────────────
if [ -d "${TARGET_DIR}" ]; then
  echo "⚠️  Target directory exists: ${TARGET_DIR}"
  echo "   Pulling latest instead of cloning..."
  cd "${TARGET_DIR}"
  git stash 2>/dev/null || true
  git checkout "${BRANCH}"
  git pull origin "${BRANCH}"
else
  echo "📦 Cloning ComplianceOS from ${REPO_URL}..."
  git clone --depth=1 --branch "${BRANCH}" "${REPO_URL}" "${TARGET_DIR}"
  cd "${TARGET_DIR}"
fi

# ── Generate .env if missing ────────────────────────────────────────────────
if [ ! -f .env ]; then
  echo "🔧 Creating .env from template..."
  cat > .env <<-ENVEOF
# ComplianceOS — generated by install.sh
# Override any value by editing this file, then: docker compose -f ${COMPOSE_FILE} up -d

# Database (defaults to embedded postgres container)
DATABASE_URL=postgres://complianceos:complianceos@db:5432/complianceos?sslmode=disable

# Encryption key — REQUIRED for production
APP_ENCRYPTION_KEY=${ENCRYPTION_KEY:-change-me-to-a-random-32-char-key}

# Auth — leave empty to use local auth (built-in)
VITE_SUPABASE_URL=
VITE_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=

# Edition — false for AGPL community, true for premium features
VITE_ENABLE_PREMIUM=true
VITE_LICENSE_KEY=community

# Telemetry — disabled by default for self-host
NO_TELEMETRY=true
ENABLE_AI=false
ENVEOF
  echo "   Edit .env to customize, then re-run the install script."
else
  echo "✅ .env already exists — keeping existing config."
fi

# ── Start ────────────────────────────────────────────────────────────────────
echo "🚀 Starting ComplianceOS..."
echo "   Port: ${PORT}"
echo ""

# Override port in compose if different from default
if [ "${PORT}" != "3002" ]; then
  export COMPOSEOS_PORT="${PORT}"
  docker compose -f "${COMPOSE_FILE}" up -d --build -e PORT="${PORT}"
else
  docker compose -f "${COMPOSE_FILE}" up -d --build
fi

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  ✅ ComplianceOS is running!                  ║"
echo "║                                               ║"
echo "║  Visit:  http://localhost:${PORT}                  ║"
echo "║  Health: http://localhost:${PORT}/health          ║"
echo "║                                               ║"
echo "║  Logs:   docker compose -f ${COMPOSE_FILE} logs -f    ║"
echo "║  Stop:   docker compose -f ${COMPOSE_FILE} down        ║"
echo "║  Update: curl -fsSL https://raw.githubusercontent.com/sectutor/ComplianceOS/main/deploy/docker/install.sh | bash"
echo "╚══════════════════════════════════════════════╝"
