#!/usr/bin/env bash
# =============================================================================
# ComplianceOS — One-Command Docker Install
# =============================================================================
# Run:
#   curl -fsSL https://grcompliance.com/install.sh | bash
#
# Or with env overrides:
#   curl -fsSL https://grcompliance.com/install.sh | \
#     bash -s -- -p 8080 -k my-encryption-key
# =============================================================================
set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
IMAGE="${IMAGE:-ghcr.io/sectutor/complianceos-self-hosted:dev}"
PORT="${PORT:-3002}"
ENCRYPTION_KEY="${APP_ENCRYPTION_KEY:-}"
TARGET_DIR="${HOME}/complianceos"

# Parse CLI flags
while [[ $# -gt 0 ]]; do
  case "$1" in
    -d|--dir)       TARGET_DIR="$2"; shift 2 ;;
    -p|--port)      PORT="$2";        shift 2 ;;
    -k|--key)       ENCRYPTION_KEY="$2"; shift 2 ;;
    -h|--help)      echo "Usage: $0 [-d dir] [-p port] [-k encryption_key]"; exit 0 ;;
    *)              echo "Unknown: $1"; exit 1 ;;
  esac
done

echo "╔══════════════════════════════════════════════╗"
echo "║     ComplianceOS — Docker Install            ║"
echo "╚══════════════════════════════════════════════╝"

# ── Prerequisites ────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || {
  echo "❌ Docker not found. Install Docker first:"
  echo "   https://docs.docker.com/engine/install/"
  exit 1
}

# ── Create target directory ──────────────────────────────────────────────────
mkdir -p "${TARGET_DIR}"
cd "${TARGET_DIR}"

# ── Generate compose file ────────────────────────────────────────────────────
cat > docker-compose.yml <<-COMPOSEEOF
services:
  complianceos:
    image: ${IMAGE}
    ports:
      - "${PORT}:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DATABASE_URL=\${DATABASE_URL:-postgres://complianceos:***@db:5432/complianceos?sslmode=disable}
      - ENCRYPTION_KEY=\${ENCRYPTION_KEY:-change-me-to-a-random-32-char-key}
      - APP_ENCRYPTION_KEY=\${ENCRYPTION_KEY:-change-me-to-a-random-32-char-key}
      - VITE_SUPABASE_URL=\${VITE_SUPABASE_URL:-}
      - VITE_SUPABASE_ANON_KEY=\${VITE_SUPABASE_ANON_KEY:-}
      - SUPABASE_SERVICE_ROLE_KEY=\${SUPABASE_SERVICE_ROLE_KEY:-}
      - VITE_ENABLE_PREMIUM=\${VITE_ENABLE_PREMIUM:-false}
      - VITE_LICENSE_KEY=\${VITE_LICENSE_KEY:-community}
      - NO_TELEMETRY=\${NO_TELEMETRY:-true}
      - ENABLE_AI=\${ENABLE_AI:-false}
      - CORS_ORIGIN=\${CORS_ORIGIN:-http://localhost:${PORT}}
    volumes:
      - complianceos_uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: complianceos
      POSTGRES_PASSWORD: complianceos
      POSTGRES_DB: complianceos
    volumes:
      - complianceos_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U complianceos"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks: {}
volumes:
  complianceos_db:
  complianceos_uploads:
COMPOSEEOF

# ── Generate .env if missing ────────────────────────────────────────────────
if [ ! -f .env ]; then
  echo "🔧 Creating .env from template..."
  cat > .env <<-ENVEOF
# ComplianceOS — generated by install.sh
# Database (defaults to embedded postgres container)
DATABASE_URL=postgres://complianceos:***@db:5432/complianceos?sslmode=disable

# Encryption key — set a random value for production
ENCRYPTION_KEY=${ENCRYPTION_KEY:-change-me-to-a-random-32-char-key}

# Supabase — leave empty for local auth (built-in)
VITE_SUPABASE_URL=
VITE_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=

# Edition
VITE_ENABLE_PREMIUM=false
VITE_LICENSE_KEY=community

# Telemetry
NO_TELEMETRY=true
ENABLE_AI=false
ENVEOF
  echo "   Edit .env to customize, then re-run the install script."
else
  echo "✅ .env already exists — keeping existing config."
fi

# ── Pull image ───────────────────────────────────────────────────────────────
echo "📥 Pulling ComplianceOS image from GHCR..."
docker pull "${IMAGE}" 2>&1 | tail -3

# ── Start ────────────────────────────────────────────────────────────────────
echo "🚀 Starting ComplianceOS on port ${PORT}..."
docker compose up -d

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  ✅ ComplianceOS is running!                  ║"
echo "║                                               ║"
echo "║  Visit:  http://localhost:${PORT}                  ║"
echo "║  Health: http://localhost:${PORT}/health          ║"
echo "║                                               ║"
echo "║  Logs:   docker compose logs -f               ║"
echo "║  Stop:   docker compose down                  ║"
echo "║  Update: docker compose pull && docker compose up -d"
echo "║  Config: ${TARGET_DIR}/.env          ║"
echo "╚══════════════════════════════════════════════╝"
