import React, { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@complianceos/ui/ui/card";
import { Button } from "@complianceos/ui/ui/button";
import { Badge } from "@complianceos/ui/ui/badge";
import { 
  Inbox, 
  CheckCircle2, 
  XCircle, 
  GitPullRequest, 
  Mail, 
  ShieldAlert, 
  FileCode2, 
  ExternalLink, 
  Clock,
  Sparkles,
  AlertTriangle,
  RefreshCw
} from "lucide-react";
import { toast } from "sonner";

export function ApprovalInboxView() {
  const { data: approvals, isLoading, refetch } = trpc.teammates.listApprovals.useQuery();
  const resolveMutation = trpc.teammates.resolveApproval.useMutation({
    onSuccess: (_, variables) => {
      toast.success(
        variables.action === "approved"
          ? "Action approved! Teammate is executing changes."
          : "Action rejected. Teammate notified."
      );
      refetch();
    },
    onError: (err) => {
      toast.error(`Error resolving approval: ${err.message}`);
    }
  });

  const [selectedApproval, setSelectedApproval] = useState<any | null>(null);

  const pendingApprovals = approvals?.filter(a => a.status === "pending") || [];
  const activeItem = selectedApproval || pendingApprovals[0];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 bg-card border border-border rounded-xl p-5 shadow-sm">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
              <Inbox className="w-5 h-5 text-primary" />
              Human-in-the-Loop Approval Inbox
            </h2>
            <Badge variant="outline" className="border-amber-500/40 text-amber-600 dark:text-amber-400 bg-amber-500/10 text-xs">
              {pendingApprovals.length} Awaiting Authorization
            </Badge>
          </div>
          <p className="text-sm text-muted-foreground mt-1">
            Review and authorize high-impact actions generated by autonomous agents before they are deployed or sent.
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => refetch()}
          className="border-border text-foreground hover:bg-accent"
        >
          <RefreshCw className="w-4 h-4 mr-1.5" />
          Refresh Inbox
        </Button>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Approvals List */}
        <div className="lg:col-span-1 space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-foreground">Pending Requests</h3>
            <span className="text-xs text-muted-foreground">{pendingApprovals.length} items</span>
          </div>

          {pendingApprovals.length === 0 ? (
            <div className="p-8 border border-border rounded-xl bg-card text-center text-muted-foreground shadow-sm">
              <CheckCircle2 className="w-10 h-10 text-emerald-500 mx-auto mb-2 opacity-80" />
              <p className="text-sm font-semibold text-foreground">Inbox Zero</p>
              <p className="text-xs text-muted-foreground mt-1">All agent actions have been reviewed and approved.</p>
            </div>
          ) : (
            <div className="space-y-2.5">
              {pendingApprovals.map((item) => {
                const isSelected = activeItem?.id === item.id;
                return (
                  <div
                    key={item.id}
                    onClick={() => setSelectedApproval(item)}
                    className={`p-3.5 rounded-xl border transition-all cursor-pointer ${
                      isSelected
                        ? "bg-primary/5 border-primary shadow-sm"
                        : "bg-card border-border hover:border-border/80 hover:bg-muted/40"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex items-center gap-1.5 text-xs text-primary font-medium">
                        {item.type === "github_pr" ? (
                          <GitPullRequest className="w-3.5 h-3.5" />
                        ) : item.type === "vendor_email" ? (
                          <Mail className="w-3.5 h-3.5" />
                        ) : (
                          <ShieldAlert className="w-3.5 h-3.5" />
                        )}
                        <span>{item.teammateName}</span>
                      </div>
                      <Badge
                        variant="outline"
                        className={`text-[10px] uppercase font-bold ${
                          item.severity === "critical"
                            ? "border-rose-500/40 text-rose-600 dark:text-rose-400 bg-rose-500/10"
                            : item.severity === "high"
                            ? "border-amber-500/40 text-amber-600 dark:text-amber-400 bg-amber-500/10"
                            : "border-border text-muted-foreground"
                        }`}
                      >
                        {item.severity}
                      </Badge>
                    </div>

                    <h4 className="text-xs font-semibold text-foreground mt-1.5 line-clamp-1">{item.title}</h4>
                    <p className="text-[11px] text-muted-foreground mt-1 line-clamp-2 leading-relaxed">
                      {item.description}
                    </p>

                    <div className="text-[10px] text-muted-foreground mt-2.5 pt-2 border-t border-border flex items-center justify-between">
                      <span>{new Date(item.createdAt).toLocaleTimeString()}</span>
                      <span className="text-primary font-medium">Click to review diff →</span>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Diff & Action Panel */}
        <div className="lg:col-span-2">
          {activeItem ? (
            <div className="bg-card border border-border rounded-xl overflow-hidden shadow-sm flex flex-col h-[520px]">
              {/* Header */}
              <div className="p-4 border-b border-border flex items-start justify-between gap-4 bg-muted/30">
                <div>
                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-xs border-primary/40 text-primary bg-primary/10">
                      {activeItem.type.replace("_", " ").toUpperCase()}
                    </Badge>
                    <span className="text-xs text-muted-foreground">Generated by {activeItem.teammateName}</span>
                  </div>
                  <h3 className="text-base font-bold text-foreground mt-1">{activeItem.title}</h3>
                  <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{activeItem.description}</p>
                </div>
              </div>

              {/* Code Diff / Payload Inspector */}
              <div className="flex-1 p-4 bg-background font-mono text-xs overflow-y-auto space-y-1 text-foreground">
                <div className="text-muted-foreground text-[11px] pb-1 border-b border-border mb-2 flex items-center gap-2">
                  <FileCode2 className="w-3.5 h-3.5 text-primary" />
                  <span>Proposed Infrastructure Patch / Action Payload:</span>
                </div>
                <pre className="text-xs leading-relaxed overflow-x-auto p-3 rounded-lg bg-muted/40 border border-border text-foreground">
                  {activeItem.diffOrPayload}
                </pre>
              </div>

              {/* Action Buttons Footer */}
              <div className="p-4 bg-card border-t border-border flex items-center justify-between">
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <AlertTriangle className="w-4 h-4 text-amber-500" />
                  <span>Approving executes the changes directly in the target environment.</span>
                </div>
                <div className="flex items-center gap-2">
                  <Button
                    size="sm"
                    variant="outline"
                    disabled={resolveMutation.isLoading}
                    onClick={() => resolveMutation.mutate({ approvalId: activeItem.id, action: "rejected" })}
                    className="border-border text-rose-600 hover:text-rose-700 hover:bg-rose-50 dark:hover:bg-rose-950/20"
                  >
                    <XCircle className="w-4 h-4 mr-1.5" />
                    Reject
                  </Button>
                  <Button
                    size="sm"
                    disabled={resolveMutation.isLoading}
                    onClick={() => resolveMutation.mutate({ approvalId: activeItem.id, action: "approved" })}
                    className="bg-emerald-600 hover:bg-emerald-500 text-white font-medium shadow-sm"
                  >
                    <CheckCircle2 className="w-4 h-4 mr-1.5" />
                    Approve & Deploy Patch
                  </Button>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-card border border-border rounded-xl h-[520px] flex flex-col items-center justify-center text-center p-6 text-muted-foreground shadow-sm">
              <Inbox className="w-12 h-12 text-muted-foreground/40 mb-3" />
              <h4 className="text-base font-semibold text-foreground">No Approval Selected</h4>
              <p className="text-xs text-muted-foreground max-w-sm mt-1">
                Select a pending authorization item to inspect the proposed code diff or payload.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
