import { useState } from "react";
import { Button } from "@complianceos/ui/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@complianceos/ui/ui/card";
import { Checkbox } from "@complianceos/ui/ui/checkbox";
import { Input } from "@complianceos/ui/ui/input";
import { Label } from "@complianceos/ui/ui/label";
import { Separator } from "@complianceos/ui/ui/separator";
import { Switch } from "@complianceos/ui/ui/switch";
import { Textarea } from "@complianceos/ui/ui/textarea";
import { toast } from "sonner";
import {
    FileText,
    Shield,
    AlertTriangle,
    CheckCircle2,
    BarChart3,
    GripVertical,
    Plus,
    Sparkles,
    Download,
    Settings2
} from "lucide-react";
import { cn } from "@/lib/utils";

interface ReportBuilderProps {
    clientId: number;
    onGenerate: (config: ReportConfig) => void;
}

export interface ReportConfig {
    title: string;
    description: string;
    sections: {
        executiveSummary: boolean;
        complianceScore: boolean;
        controlsMatrix: boolean;
        policyStatus: boolean;
        riskRegister: boolean;
        evidenceLog: boolean;
    };
    includeCharts: boolean;
    includeBranding: boolean;
}

export function ReportBuilder({ clientId, onGenerate }: ReportBuilderProps) {
    const [config, setConfig] = useState<ReportConfig>({
        title: "Custom Compliance Report",
        description: "Generated by ComplianceOS",
        sections: {
            executiveSummary: true,
            complianceScore: true,
            controlsMatrix: true,
            policyStatus: false,
            riskRegister: false,
            evidenceLog: false,
        },
        includeCharts: true,
        includeBranding: true,
    });

    const modules = [
        { id: 'executiveSummary', label: 'Executive Insights', icon: <Sparkles className="h-4 w-4 text-indigo-500" />, description: 'AI-driven summary and high-level observations' },
        { id: 'complianceScore', label: 'Compliance Analytics', icon: <BarChart3 className="h-4 w-4 text-blue-500" />, description: 'Score trajectory, gap analysis heatmaps' },
        { id: 'controlsMatrix', label: 'Controls Matrix', icon: <Shield className="h-4 w-4 text-green-500" />, description: 'Detailed status of all mapped controls' },
        { id: 'policyStatus', label: 'Policy Coverage', icon: <FileText className="h-4 w-4 text-amber-500" />, description: 'Adherence and approval status of governance documents' },
        { id: 'riskRegister', label: 'Risk Register', icon: <AlertTriangle className="h-4 w-4 text-red-500" />, description: 'Top risks, heatmaps, and treatment plans' },
        { id: 'evidenceLog', label: 'Evidence Audit Log', icon: <CheckCircle2 className="h-4 w-4 text-slate-500" />, description: 'Recent verification activities and file links' },
    ];

    const handleToggle = (key: keyof typeof config.sections) => {
        setConfig(prev => ({
            ...prev,
            sections: {
                ...prev.sections,
                [key]: !prev.sections[key]
            }
        }));
    };

    const handleGenerate = () => {
        toast.success("Compiling custom report configuration...");
        onGenerate(config);
    };

    return (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 animate-in fade-in slide-in-from-bottom-4">
            {/* Configuration Column */}
            <div className="lg:col-span-2 space-y-6">
                <Card className="border-0 shadow-md bg-white/80 backdrop-blur-sm">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Settings2 className="h-5 w-5 text-indigo-600" />
                            Report Configuration
                        </CardTitle>
                        <CardDescription>Customize the content and structure of your compliance report.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="grid gap-4">
                            <div className="grid gap-2">
                                <Label htmlFor="title">Report Title</Label>
                                <Input
                                    id="title"
                                    value={config.title}
                                    onChange={(e) => setConfig({ ...config, title: e.target.value })}
                                    className="font-medium text-lg"
                                />
                            </div>
                            <div className="grid gap-2">
                                <Label htmlFor="desc">Description / Subtitle</Label>
                                <Textarea
                                    id="desc"
                                    value={config.description}
                                    onChange={(e) => setConfig({ ...config, description: e.target.value })}
                                    className="resize-none"
                                    rows={2}
                                />
                            </div>
                        </div>

                        <Separator />

                        <div>
                            <Label className="text-base font-semibold mb-4 block">Select Modules</Label>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                {modules.map((module) => (
                                    <div
                                        key={module.id}
                                        className={cn(
                                            "flex items-start gap-4 p-4 rounded-xl border transition-all cursor-pointer hover:shadow-md",
                                            config.sections[module.id as keyof typeof config.sections]
                                                ? "bg-indigo-50/50 border-indigo-200 shadow-sm"
                                                : "bg-white border-slate-200 opacity-80 hover:opacity-100"
                                        )}
                                        onClick={() => handleToggle(module.id as keyof typeof config.sections)}
                                    >
                                        <Checkbox
                                            checked={config.sections[module.id as keyof typeof config.sections]}
                                            className="mt-1"
                                        />
                                        <div className="space-y-1">
                                            <div className="font-medium flex items-center gap-2">
                                                {module.icon}
                                                {module.label}
                                            </div>
                                            <p className="text-xs text-slate-500 leading-snug">
                                                {module.description}
                                            </p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        <Separator />

                        <div className="flex items-center justify-between">
                            <Label className="flex flex-col gap-1">
                                <span className="font-medium">Include Charts & Visuals</span>
                                <span className="text-xs text-slate-500 font-normal">Render visual analytics graphs in the PDF</span>
                            </Label>
                            <Switch
                                checked={config.includeCharts}
                                onCheckedChange={(c) => setConfig({ ...config, includeCharts: c })}
                            />
                        </div>
                        <div className="flex items-center justify-between">
                            <Label className="flex flex-col gap-1">
                                <span className="font-medium">White-labeled Branding</span>
                                <span className="text-xs text-slate-500 font-normal">Use your company logo and colors</span>
                            </Label>
                            <Switch
                                checked={config.includeBranding}
                                onCheckedChange={(c) => setConfig({ ...config, includeBranding: c })}
                            />
                        </div>

                    </CardContent>
                    <CardFooter className="bg-slate-50/50 border-t p-6 flex justify-between items-center">
                        <div className="text-xs text-slate-500 italic">
                            Estimated pages: {
                                Object.values(config.sections).filter(Boolean).length * 2 + 1
                            }
                        </div>
                        <Button size="lg" onClick={handleGenerate} className="gap-2 bg-indigo-600 hover:bg-indigo-700">
                            <Download className="h-4 w-4" /> Generate Custom Report
                        </Button>
                    </CardFooter>
                </Card>
            </div>

            {/* Preview Column */}
            <div className="space-y-6">
                <Card className="bg-slate-50 border-dashed border-2 shadow-none h-full max-h-[700px] overflow-hidden sticky top-6">
                    <CardHeader>
                        <CardTitle className="text-sm uppercase tracking-wider text-slate-500">Live Preview (Structure)</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="bg-white shadow-xl aspect-[1/1.4] w-full p-8 text-[8px] md:text-[10px] space-y-4 border rounded-sm overflow-hidden opacity-90 transition-all">
                            {/* Header Preview */}
                            <div className="flex justify-between items-center border-b pb-4">
                                <div className="space-y-1">
                                    {config.includeBranding && <div className="h-4 w-12 bg-indigo-600 rounded-sm mb-2" />}
                                    <div className="font-bold text-slate-800 text-xs w-3/4">{config.title || "Report Title"}</div>
                                    <div className="text-slate-400">{new Date().toLocaleDateString()}</div>
                                </div>
                                <div className="h-8 w-8 bg-slate-100 rounded-full" />
                            </div>

                            {/* TOC Preview based on selection */}
                            <div className="space-y-2">
                                <div className="h-2 w-20 bg-slate-100 rounded" />
                                {config.sections.executiveSummary && <div className="h-2 w-full bg-indigo-500/10 rounded" />}
                                {config.sections.complianceScore && <div className="h-24 w-full bg-blue-100/50 rounded flex items-center justify-center text-blue-300">Analytics Chart</div>}
                                {config.sections.controlsMatrix && (
                                    <div className="space-y-1 mt-2">
                                        <div className="h-2 w-full bg-slate-100 rounded" />
                                        <div className="h-2 w-full bg-slate-100 rounded" />
                                        <div className="h-2 w-[80%] bg-slate-100 rounded" />
                                    </div>
                                )}
                                {config.sections.policyStatus && <div className="h-16 w-full bg-amber-50/50 rounded mt-2 border border-amber-100" />}
                                {config.sections.riskRegister && <div className="h-16 w-full bg-red-50/50 rounded mt-2 border border-red-100" />}
                            </div>

                            {/* Footer Preview */}
                            <div className="absolute bottom-8 left-8 right-8 border-t pt-2 flex justify-between text-slate-300">
                                <span>Page 1</span>
                                <span>Confidential</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
