/**
 * RFC 7807 Problem Details for HTTP APIs
 * https://tools.ietf.org/html/rfc7807
 *
 * Standardized error response shape for RESTful API endpoints.
 */

/** RFC 7807 Problem Details structure */
export interface ProblemDetail {
  /** A URI reference that identifies the problem type */
  type: string;
  /** A short, human-readable summary of the problem type */
  title: string;
  /** The HTTP status code generated by the origin server */
  status: number;
  /** A human-readable explanation specific to this occurrence */
  detail: string;
  /** A URI reference that identifies the specific occurrence */
  instance?: string;
  /** Optional error bag for validation errors */
  errors?: Record<string, string[]>;
}

/** Options for creating a Problem Detail */
export interface ProblemDetailOptions {
  type?: string;
  title?: string;
  status: number;
  detail: string;
  instance?: string;
  errors?: Record<string, string[]>;
}

/** Default type URI prefix */
const DEFAULT_TYPE_PREFIX = 'https://complianceos.intellfence.com/problems';

/**
 * Creates an RFC 7807 compliant Problem Detail object.
 */
export function createProblemDetail(options: ProblemDetailOptions): ProblemDetail {
  const {
    type = `${DEFAULT_TYPE_PREFIX}/generic`,
    title,
    status,
    detail,
    instance,
    errors,
  } = options;

  const problem: ProblemDetail = {
    type,
    title: title ?? getDefaultTitle(status),
    status,
    detail,
  };

  if (instance) {
    problem.instance = instance;
  }

  if (errors) {
    problem.errors = errors;
  }

  return problem;
}

/** Returns a default title based on HTTP status code */
function getDefaultTitle(status: number): string {
  switch (status) {
    case 400:
      return 'Bad Request';
    case 401:
      return 'Unauthorized';
    case 403:
      return 'Forbidden';
    case 404:
      return 'Not Found';
    case 409:
      return 'Conflict';
    case 422:
      return 'Unprocessable Entity';
    case 429:
      return 'Too Many Requests';
    case 500:
      return 'Internal Server Error';
    case 502:
      return 'Bad Gateway';
    case 503:
      return 'Service Unavailable';
    default:
      return 'Error';
  }
}

/**
 * Creates a 400 Bad Request Problem Detail.
 */
export function badRequest(
  detail = 'The request was invalid.',
  errors?: Record<string, string[]>
): ProblemDetail {
  return createProblemDetail({
    type: `${DEFAULT_TYPE_PREFIX}/bad-request`,
    status: 400,
    detail,
    errors,
  });
}

/**
 * Creates a 401 Unauthorized Problem Detail.
 */
export function unauthorized(detail = 'Authentication is required.'): ProblemDetail {
  return createProblemDetail({
    type: `${DEFAULT_TYPE_PREFIX}/unauthorized`,
    status: 401,
    detail,
  });
}

/**
 * Creates a 403 Forbidden Problem Detail.
 */
export function forbidden(detail = 'You do not have permission to access this resource.'): ProblemDetail {
  return createProblemDetail({
    type: `${DEFAULT_TYPE_PREFIX}/forbidden`,
    status: 403,
    detail,
  });
}

/**
 * Creates a 404 Not Found Problem Detail.
 */
export function notFound(resource?: string, detail?: string): ProblemDetail {
  const resolvedDetail = detail ?? (resource ? `The requested ${resource} was not found.` : 'The requested resource was not found.');
  return createProblemDetail({
    type: `${DEFAULT_TYPE_PREFIX}/not-found`,
    status: 404,
    detail: resolvedDetail,
  });
}

/**
 * Creates a 409 Conflict Problem Detail.
 */
export function conflict(detail = 'The request conflicts with the current state.'): ProblemDetail {
  return createProblemDetail({
    type: `${DEFAULT_TYPE_PREFIX}/conflict`,
    status: 409,
    detail,
  });
}

/**
 * Creates a 422 Unprocessable Entity Problem Detail.
 */
export function unprocessableEntity(
  detail = 'The request was well-formed but contains semantic errors.',
  errors?: Record<string, string[]>
): ProblemDetail {
  return createProblemDetail({
    type: `${DEFAULT_TYPE_PREFIX}/unprocessable-entity`,
    status: 422,
    detail,
    errors,
  });
}

/**
 * Creates a 429 Too Many Requests Problem Detail.
 */
export function tooManyRequests(detail = 'Rate limit exceeded. Try again later.'): ProblemDetail {
  return createProblemDetail({
    type: `${DEFAULT_TYPE_PREFIX}/too-many-requests`,
    status: 429,
    detail,
  });
}

/**
 * Creates a 500 Internal Server Error Problem Detail.
 */
export function internal(detail = 'An unexpected error occurred.'): ProblemDetail {
  return createProblemDetail({
    type: `${DEFAULT_TYPE_PREFIX}/internal`,
    status: 500,
    detail,
  });
}

/**
 * Type guard that checks if a value is a valid Problem Detail object.
 */
export function isProblemDetail(value: unknown): value is ProblemDetail {
  if (value === null || typeof value !== 'object') {
    return false;
  }

  const obj = value as Record<string, unknown>;

  // Required fields
  if (typeof obj['type'] !== 'string') return false;
  if (typeof obj['title'] !== 'string') return false;
  if (typeof obj['status'] !== 'number') return false;
  if (typeof obj['detail'] !== 'string') return false;

  // Optional fields
  if (obj['instance'] !== undefined && typeof obj['instance'] !== 'string') return false;
  if (obj['errors'] !== undefined) {
    if (typeof obj['errors'] !== 'object' || obj['errors'] === null) return false;
    const errors = obj['errors'] as Record<string, unknown>;
    for (const key of Object.keys(errors)) {
      const val = errors[key];
      if (!Array.isArray(val)) return false;
      if (!val.every((item) => typeof item === 'string')) return false;
    }
  }

  return true;
}
