#!/usr/bin/env bash
# ============================================================================
# ComplianceOS Self-Host Setup Script
# Interactive one-command setup for new deployments.
#
# Usage: bash scripts/setup.sh
#   or:  chmod +x scripts/setup.sh && ./scripts/setup.sh
#
# Generates .env from your answers, then prints the docker-compose command.
# ============================================================================

set -e

# Colors
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   ComplianceOS Self-Host — Quick Setup      ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo "This will create a .env file for your deployment."
echo "Press Enter to accept defaults shown in [brackets]."
echo ""

# --- Helper ---
prompt() {
  local var_name="$1"
  local label="$2"
  local default="$3"
  local secret="$4"
  local val

  if [ "$secret" = "true" ]; then
    read -s -p "  $label [$default]: " val
    echo ""
  else
    read -p "  $label [$default]: " val
  fi

  if [ -z "$val" ]; then
    val="$default"
  fi

  eval "$var_name=\"$val\""
}

# --- Step 1: Edition ---
echo -e "${BOLD}Step 1: Edition${NC}"
echo "  Choose Community (free, AGPLv3) or Premium (paid, Pro/Enterprise)."
echo "  Premium requires a license key from ComplianceOS."
echo ""
prompt EDITION "Edition (community/premium)" "community"
echo ""

if [ "$EDITION" = "premium" ]; then
  prompt VITE_ENABLE_PREMIUM "Enable Premium" "true"
  prompt VITE_LICENSE_KEY "License Key" ""
else
  VITE_ENABLE_PREMIUM="false"
  VITE_LICENSE_KEY=""
fi

# --- Step 2: Database ---
echo -e "${BOLD}Step 2: Database${NC}"
echo "  ComplianceOS requires PostgreSQL. Provide a connection string,"
echo "  or leave blank to use the Docker Compose Postgres container."
echo ""
prompt DATABASE_URL "Database URL (postgres://user:pass@host:5432/db)" "postgres://complianceos:complianceos@db:5432/complianceos"
echo ""

# --- Step 3: Encryption ---
echo -e "${BOLD}Step 3: Encryption${NC}"
echo -e "  ${YELLOW}REQUIRED in production.${NC} Generates AES-256 key for credential encryption."
echo "  Leave blank to auto-generate."
echo ""
DEFAULT_KEY=$(openssl rand -base64 32 2>/dev/null || echo "change-me-to-a-random-key")
prompt APP_ENCRYPTION_KEY "Encryption key" "$DEFAULT_KEY"
echo ""

# --- Step 4: Supabase ---
echo -e "${BOLD}Step 4: Authentication (Supabase)${NC}"
echo "  ComplianceOS uses Supabase for authentication."
echo "  Create a free project at https://supabase.com and enter the URL and anon key."
echo "  Leave blank for local-only auth (single user, dev mode)."
echo ""
prompt VITE_SUPABASE_URL "Supabase URL" ""
if [ -n "$VITE_SUPABASE_URL" ]; then
  prompt VITE_SUPABASE_ANON_KEY "Supabase Anon Key" ""
  prompt SUPABASE_SERVICE_ROLE_KEY "Supabase Service Role Key" "" true
fi
echo ""

# --- Step 5: Telemetry ---
echo -e "${BOLD}Step 5: Telemetry & AI${NC}"
echo "  ComplianceOS phones home for license validation only."
echo "  Set NO_TELEMETRY=true for air-gapped deployments."
echo "  AI features require ENABLE_AI=true + LLM API keys in .env."
echo ""
prompt NO_TELEMETRY "Block non-essential outbound? (true/false)" "false"
prompt ENABLE_AI "Enable AI drafting? (true/false)" "false"
echo ""

# --- Step 6: Email ---
echo -e "${BOLD}Step 6: Email (optional)${NC}"
echo "  For purchase receipts and license notifications."
echo "  Supports Resend (recommended) or SMTP."
echo "  Leave blank to skip email setup."
echo ""
prompt RESEND_API_KEY "Resend API Key" ""
if [ -z "$RESEND_API_KEY" ]; then
  prompt SMTP_HOST "SMTP Host" ""
  prompt SMTP_PORT "SMTP Port" "587"
  prompt SMTP_USER "SMTP User" ""
  prompt SMTP_PASS "SMTP Password" "" true
fi
echo ""

# --- Generate .env ---
cat > .env << EOF
# =============================================================================
# ComplianceOS — Generated by setup.sh on $(date)
# =============================================================================

# Database
DATABASE_URL="${DATABASE_URL}"

# Encryption
APP_ENCRYPTION_KEY="${APP_ENCRYPTION_KEY}"

# License
VITE_ENABLE_PREMIUM="${VITE_ENABLE_PREMIUM}"
VITE_LICENSE_KEY="${VITE_LICENSE_KEY}"

# Auth
VITE_SUPABASE_URL="${VITE_SUPABASE_URL}"
VITE_SUPABASE_ANON_KEY="${VITE_SUPABASE_ANON_KEY}"
SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY}"

# Telemetry & AI
NO_TELEMETRY="${NO_TELEMETRY}"
ENABLE_AI="${ENABLE_AI}"

# Email
RESEND_API_KEY="${RESEND_API_KEY}"
SMTP_HOST="${SMTP_HOST}"
SMTP_PORT="${SMTP_PORT}"
SMTP_USER="${SMTP_USER}"
SMTP_PASS="${SMTP_PASS}"

# Rate limiting (on by default)
RATE_LIMITING_ENABLED=true

# CORS
CORS_ORIGIN=http://localhost:3002
EOF

# --- Done ---
echo ""
echo -e "${GREEN}${BOLD}✓ .env file created successfully${NC}"
echo ""
echo "Next steps:"
echo "  1. Review .env for any missing values"
echo "  2. Start the services:"
echo ""
echo -e "     ${BOLD}docker compose -f docker-compose.selfhost.yml up -d${NC}"
echo ""
echo "  3. Run migrations:"
echo ""
echo -e "     ${BOLD}docker exec complianceos-complianceos-1 npx drizzle-kit push:pg${NC}"
echo ""
echo "  4. Verify health:"
echo ""
echo -e "     ${BOLD}curl http://localhost:3002/health${NC}"
echo ""

# --- Security Check ---
if [ "$EDITION" = "community" ]; then
  echo -e "  ${YELLOW}Community Edition: AI and multi-tenancy features are disabled.${NC}"
  echo -e "  ${YELLOW}Set VITE_ENABLE_PREMIUM=true and get a license key to unlock them.${NC}"
fi

if [ -z "$VITE_SUPABASE_URL" ]; then
  echo -e "  ${YELLOW}No Supabase configured — running in local-only auth mode.${NC}"
  echo -e "  ${YELLOW}Only local admin user will be able to log in.${NC}"
fi

echo ""
